cache: cargo
dist: trusty
language: rust
rust: nightly
services: docker
sudo: required

matrix:
  include:
    - env: TARGET=aarch64-unknown-linux-gnu
    - env: TARGET=armv7-unknown-linux-gnueabihf
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=mips-unknown-linux-gnu
    - env: TARGET=mips64-unknown-linux-gnuabi64
    - env: TARGET=mips64el-unknown-linux-gnuabi64
    - env: TARGET=mipsel-unknown-linux-gnu
    - env: TARGET=powerpc-unknown-linux-gnu
    - env: TARGET=powerpc64-unknown-linux-gnu
    - env: TARGET=powerpc64le-unknown-linux-gnu
    - env: TARGET=s390x-unknown-linux-gnu
env: TARGET=x86_64-unknown-linux-gnu

install:
  - sh ci/install.sh
  - source ~/.cargo/env

script:
  - bash ci/script.sh

before_cache:
  - sh ci/before_cache.sh

after_success:
  - sh ci/after_success.sh

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    releases: W1xJIL2bOdrnu0qfqmfMBV9TF34YqmzZzNL9GU9/fpFb/2+cRjBGYxJLRQ2v7wD5B2ThLJAi/NXMG2YjC/gDAu4zjAkshMeKPKGvcu4PgPSEwNYL0C6ubcU6pO2rDmfUv4v/0Urk3LkpzUHkYGSXE7zFOM3zOiMbqryuO9EtYerZoj319/P3vnJaBIEtdFgdLZwLwoHWna/oFq/PU5HsdWWpxD9DYbCmCax16Vyt5UxFkMkU49XYgMspOGDZHSrb/WTvyIZ3hWyu5x5FkpvjQ5Dk00IdXB0cg6biuaryOgN+lXw2TZCSvmZOw4qOcnF+adzy8mOJMGjrCxGbF8Nmq1yM9+9+hkys0mvQKYhxuuKB9Rx7w5PAuGX9vCv4p5Is8xxX6UnB5eaNvTtVpZBFSLdQQEDTzULOxrfHRNDnzXQKj4vvGdo8rVv82GtRgWO99w23OVO8dKdpZ7RSgyuz7haHmJTSw1s7GPcrEfJ+ebEpJNm/RBHYmhfqD8T7V/jkHBgC4x1kpDoBBfbfdfV8OE5Evl8zgz8ygsmbPHFSl+ngj/pLaewI9JL2sP28e8jVhn40vEldBg7lLyGvwNJqsFNOtk+p09Rbs3IgX2iLkUvXnjIJqFtTdSoPLt4me8GRPfg34NcMeUCtwc0h/LLrlUZiHK7hvnRqZLWEaYDEHR8=
  file_glob: true
  file: *-$TRAVIS_TAG-$TARGET.*
  skip_cleanup: true
  on:
    condition: $TARGET = x86_64-unknown-linux-gnu
    tags: true

branches:
  only:
    - /^v\d+\.\d+\.\d+.*$/
    - auto
    - master
    - try

cache:
  directories:
    - cache

notifications:
  email:
    on_success: never
