dist: trusty
language: rust
rust: nightly
services: docker
sudo: required

matrix:
  include:
    - env: TARGET=aarch64-unknown-linux-gnu
    - env: TARGET=armv7-unknown-linux-gnueabihf
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=mips-unknown-linux-gnu
    - env: TARGET=mips64-unknown-linux-gnuabi64
    - env: TARGET=mips64el-unknown-linux-gnuabi64
    - env: TARGET=mipsel-unknown-linux-gnu
    - env: TARGET=powerpc-unknown-linux-gnu
    - env: TARGET=powerpc64-unknown-linux-gnu
    - env: TARGET=powerpc64le-unknown-linux-gnu
    - env: TARGET=s390x-unknown-linux-gnu
env: TARGET=x86_64-unknown-linux-gnu

install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $TRAVIS_RUST_VERSION
  - source ~/.cargo/env

script:
  - cargo install --path .
  - docker pull japaric/$TARGET
  - ./build-docker-image.sh $TARGET
  - git clone --depth 1 https://github.com/rust-lang/cargo
  - ( cd cargo && cross build --target $TARGET )
  - git clone --depth 1 https://github.com/rust-lang-nursery/compiler-builtins
  - ( cd compiler-builtins && cross test --target $TARGET )

branches:
  only:
    - master

notifications:
  email:
    on_success: never
