[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>", "Markus Reiter <me@reitermark.us>"]
build = "build.rs"
description = "Zero setup cross compilation and cross testing"
documentation = "https://github.com/cross-rs/cross"
keywords = ["cross", "compilation", "testing", "tool"]
license = "MIT OR Apache-2.0"
name = "cross"
repository = "https://github.com/cross-rs/cross"
version = "0.2.1"
edition = "2018"

[dependencies]
atty = "0.2"
color-eyre = "0.6.1"
eyre = "0.6.7"
home = "0.5"
lazy_static = "1.0"
libc = "0.2.104"
rustc_version = "0.4"
toml = "0.5"
which = { version = "4", default_features = false }
shell-escape = "0.1.4"
serde_json = "1.0.48"

[target.'cfg(not(windows))'.dependencies]
nix = "0.23"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.7", features = ["winbase"] }

[profile.release]
lto = true
